---
title: "GAV Families"
author: "Cheryl"
date: "28 November 2019"
output: html_document
---

#All Cohorts Families

#To view GAV loads of all families using ggplot2
```{r}
library(tidyverse) ## Do this everytime you restart R and need it
library(ggplot2)
```

#Import dataset of all cohorts families
```{r}
allfams <- read_csv("https://raw.githubusercontent.com/cheryltky/ViralTransmission/master/Working%20Files/allcohortfamsv2.csv")
head(allfams)
summary(allfams)
str(allfams)
```

# Make PrawnID, Class, Age, FamID , IntFamID as factors

```{r}
allfams <- allfams %>% mutate_if(is.character, as.factor)
allfams$IntFamID <- as.factor(allfams$IntFamID)
allfams$PrawnID <- as.factor(allfams$PrawnID)
allfams$Class <- as.factor(allfams$Class)
allfams$Age <- as.factor(allfams$Age)
allfams$Cohort <- as.factor(allfams$Cohort)
allfams$FamID <- as.factor(allfams$FamID)
str(allfams)
summary(allfams)
```

##Scatterplot by families

```{r}
ggplot(allfams , aes(IntFamID , GAV)) +
  geom_point() +
  theme_classic()
```

##Boxplot by families
```{r}
ggplot(allfams , aes(IntFamID , GAV)) +
  geom_jitter(width = 0.2) +
  aes(color = Age , shape = Class ) +
  labs( title = "All families GAV loads")

allcohortfams <- ggplot(allfams , aes(IntFamID , GAV)) +
  geom_jitter(width = 0.2) +
  aes(color = Age , shape = Class ) +
  labs( title = "All Families GAV Loads",
        x = "Family" , 
        y = "GAV RNA copies/ug TNA")

allcohortfams
ggsave("allcohortfams.png" , allcohortfams , width = 15, height = 10 , dpi = 300)
```


##Import dataset for 11 families from cohorts20160204

```{r}
toptenfams <- read_csv("https://raw.githubusercontent.com/cheryltky/ViralTransmission/master/Working%20Files/20160204topfams.csv")
head(toptenfams)
str(toptenfams)
summary(toptenfams)
```

## Make PrawnID, Class, Age, FamID , IntFamID as factors
```{r}
toptenfams$IntFamID <- as.factor(toptenfams$IntFamID)
toptenfams$PrawnID <- as.factor(toptenfams$PrawnID)
toptenfams$Class <- as.factor(toptenfams$Class)
toptenfams$Age <- as.factor(toptenfams$Age)
toptenfams$Cohort <- as.factor(toptenfams$Cohort)
toptenfams$FamID <- as.factor(toptenfams$FamID)
str(toptenfams)
summary(toptenfams)
```

## Scatterplot of top 11 20160204 families
```{r}
ggplot(toptenfams , aes(IntFamID, GAV)) +
  geom_point() + 
  theme_classic()
```

# Boxplot of top 11 20160204 families
```{r}
ggplot(toptenfams , aes(IntFamID, GAV)) +
  geom_jitter(width = 0.2) +
  aes(color = Age, shape = Class) +
  labs(title = "Top 11 20160204 GAV families",
       x = "Family ID",
       y = "Log10GAV copies/ug TNA") +
  theme_bw()
  
```

