---
title: "Graphics with ggplot2"
author: "Cheryl"
date: "05 July 2019"
output: html_document
---

#To view GAV loads of all families from 1 plate per pond using ggplot2
```{r}
library(tidyverse) ## Do this everytime you restart R and need it
library(ggplot2)
```

```{r}
families_data <- read_csv("https://raw.githubusercontent.com/cheryltky/ViralTransmission/master/Working%20Files/allcohorts_1plate_class.csv")
head(families_data)
summary(families_data)
str(families_data)
```

#make FamID a factor

```{r}
families_data $FamID <- as.factor(families_data $FamID)
summary(families_data)
```

##Scatterplot by families
```{r}
ggplot(families_data , aes(FamID , GAV)) +
  geom_point() +
  theme_classic()
```

##boxplot by families
```{r}
ggplot(families_data , aes(FamID , GAV)) +
  geom_jitter(width = 0.2) +
  aes(color = Class , shape = Class ) +
  labs( title = "All families GAV loads")

allfamplot <- ggplot(families_data , aes(FamID , GAV)) +
  geom_jitter(width = 0.2) +
  aes(color = Class , shape = Class ) +
  labs( title = "All families GAV loads")


ggsave("allfamplots.png" , allfamplot , width = 15, height = 10 , dpi = 300)
```

#read allcohorts top 10 fams 

```{r}
allcohorts_top10 <- readr::read_csv("https://raw.githubusercontent.com/cheryltky/ViralTransmission/master/Working%20Files/allcohorts_top10fams.csv")
```
#explore the top10fams dataset
```{r}
head(allcohorts_top10)
tail(allcohorts_top10)
names(allcohorts_top10)
ncol(allcohorts_top10)
summary(allcohorts_top10)
```
# make family ID a factor
```{r}
allcohorts_top10$FamilyID <- as.factor(allcohorts_top10$FamilyID)
summary(allcohorts_top10)
```

# make offspring ID , father ID, Mother ID and cohort all factors too
```{r}
allcohorts_top10$OffspringID <- as.factor(allcohorts_top10$OffspringID)
allcohorts_top10$FatherID <- as.factor(allcohorts_top10$FatherID)
allcohorts_top10$MotherID <- as.factor(allcohorts_top10$MotherID)
allcohorts_top10$Cohort <- as.factor(allcohorts_top10$Cohort)
summary(allcohorts_top10)
```



