## Influence of Viral Transmission from Broodstock to Offspring : Implications for Breeding Programs

Tan C.K.Y.a,b,c , Foote A.R. a,b,c, Wade N.M. a,c, Cowley J.A. a,c, Noble T.H.a,b,c, Giardina E.a,d Coman G.J.a,c, Jerry D.R.a,b
aARC Research Hub for Advanced Prawn Breeding, James Cook University, QLD, Australia.
bCentre for Sustainable Tropical Fisheries and Aquaculture, College of Science and Engineering, James Cook University, QLD, Australia.
cAquaculture Program, CSIRO Agriculture and Food, Queensland Bioscience Precinct, St. Lucia, QLD, 4067, Australia.
dSeafarms Group Ltd, Ella Bay Road, Flying Fish Point, QLD 4860, Australia.

#Abstract

Gill associated virus (GAV) occurs commonly in black tiger prawn (Penaeus monodon) broodstock in eastern Australia. The virus is believed to be primarily transmitted vertically from broodstock to progeny and is the major route by which infection enters farm ponds to cause disease and production losses. This study investigates the extent to which GAV infection loads in wild broodstock (n=184) are reflected in their progeny reared in commercial ponds at the time of harvest, and the extent to which vertical and/or horizontal transmission, as well as genetic differences between families, might have contributed to infection prevalence and severity between different families. This study looks at 184 broodstock animals and eight ponds of harvest age offspring across three cohorts and demonstrates the impact early-life horizontal transmission, vertical transmission and horizontal transmission have on progeny loads.


##Introduction

In eastern Australia, gill-associated virus (GAV) occurs commonly in black tiger shrimp, Penaeus monodon and is responsible for significant production losses in terms of growth and survival (de la Vega et al., 2004). While demonstrated to be transmitted vertically (Cowley et al., 2002), the implications of farming seedstock derived from wild broodstock differing in GAV infection loads have not been investigated pragmatically. To address this, SNP-based genotyping and reverse transcription real-time quantitative PCR (RT-qPCR) was used to correlate GAV infection prevalence and loads across three cohorts of wild broodstock and their progeny sampled at random at the time of harvest from ponds. 
To identify potential correlations between mean GAV viral loads and prevalence at the family, pond and cohort levels, GAV loads (viral copies/ug TNA) from broodstock and harvest age offspring were measured and compared between contributing parent pairs and corresponding progeny at harvest from three cohorts. Reverse transcriptase real time quantitative PCR (RT-qPCR) testing of total nucleic acid (TNA) extracted from pleopod tissue sampled at eye-stalk ablation was applied to all broodstock. In addition, a subset of broodstock were sampled and viral screened at pre- and post-spawn time points to demonstrate that viral infection load was influenced by stress and handling during these time points.


##Materials and Methods

Pleopod and gill tissue samples

Tissue samples from wild broodstock, post spawned broodstock and postlarval progeny of these broodstock were obtained from a commercial farm in north-east Queensland. All shrimp tissue samples were collected in 96-deepwell plates and preserved in 2mL of RNA-later solution.

TNA extraction and GAV RT-qPCR

Total RNA was extracted according to the Kingfisher extraction protocol (Table 1). A 1.5 µL aliquot was examined using a Nanodrop® ND-8000 spectrophotometer (Thermo Fisher) to determine the RNA concentration and relative purity. cDNA was synthesised in a 10 μL reaction containing 500 ng total RNA, 0.5 μL reverse transcriptase and 2 μL 5x TransAmpBuffer (Bioline Sensifast cDNA Kit). A TaqMan RT-qPCR test for GAV (de la Vega et al., 2004) was performed as described except that 2 µL cDNA (equivalent to 100 ng total RNA) was used in a 20 µL reaction prepared using TaqMan® Universal PCR Master Mix (Applied Biosystems) and 18 µM each PCR primer. From this 20 µL mixture, 3 x 5 µL aliquots were placed into 3 wells of a 384-well PCR plate as plate replicates. QPCR was performed in a Viia7® Real-Time PCR system (Applied Biosystems) using thermal cycling conditions xxxxx . To quantify GAV RNA copy numbers accurately, cDNA prepared to a 10-fold dilution series of synthetic GAV RNA of known copy number was amplified in the same plate to generate a linear regression plot of mean cycle threshold (Ct) value vs RNA copy number. Infection loads were expressed as GAV RNA copies per 1 ng total RNA to adjust for the use of cDNA prepared to 25 ng total RNA in each 5 µL reaction aliquot.

Genotyping and parentage assignment

The data used in this study were run on two platforms. Cohorts 201602 and 201604 were run on two 60-SNP marker Sequenom® iPLEX Platinum panels for the Black Tiger shrimp (AGRF , Brisbane, Australia) and cohort G1T1701 was run on a DaRTcap platform (Diversity Arrays, ACT, Australia)

Statistical Analyses

GAV RNA copy number data were adjusted to log10 scale for standardization. Families with five or more individuals per family per pond were selected. For animals tested as “zero”, these were converted to loadings of 0.0001 to avoid them dropping out of the analyses. 


##Results

1.1 Detection of GAV RNA loads pre and post-spawn in broodstock animals
Among the 28 wild broodstock animals sampled at pre-spawn, xx% of them showed a low to moderate low infection level (xx –xx GAV RNA copies/µg TNA).A second cohort (G1T1701_DBR) was tested for GAV infection loads at the same two time points and all animals showed at least a two fold increase in GAV infection levels. 
```{r load packages, echo = FALSE}
library(tidyverse)
library(ggplot2)
allbroodstock <- read_csv("https://raw.githubusercontent.com/cheryltky/ViralTransmission/master/Working%20Files/allcohorts_broodstock.csv")
head(allbroodstock)
ggplot(allbroodstock, aes(x="NO", y = "LOGGAV"))+
  geom_boxplot()+
  geom_violin()+
  geom_dotplot(binaxis='y', stackdir='center', dotsize=1)+
  theme_classic()
```


In broodstock (n=28) for which a pleopod was also sampled when culled at the end of the hatchery run, they were generally found to have increased.  GAV prevalence and loads of offspring from eight ponds were measured and compared against GAV loads from contributing parents.


#Discussion